Feature/take photo
PVB-Team-1/ProefProeveTeam1 pull request #3
Opened 2020-03-06 14:29 UTC by Vychron

2020-03-06 15:46 UTC, waffel183 requested changes
Good commits, but lacking a bit of documentation at 1 function. Fix this first before merging

2020-03-06 15:46 UTC, waffel183 commented on Assets/Scripts/Features/Gameplay/Take Photo/GeneratePhoto.cs
> +    /// <returns></returns>
Add small description of "rTex" parameter
Also add what it returns in the comment, not just <returns></returns>

2020-03-09 22:30 UTC, empireboy commented
There needs to be a private access modifier in front of your methods, as shown in the code conventions under "Access Modifiers". This will make it easier to read if your method is private, public or protected.

Also im not sure if you need those lines:
`
using System.Collections;
`
`
using System.Collections.Generic;
`
If you dont need them you need to remove them. You can also find this in the code conventions under "Using".

Code conventions:
https://docs.google.com/document/d/1ndhz6gM4dyjpbsxsPXH3Zr36-6QOn1e2/edit#

2020-03-10 11:12 UTC, waffel183 requested changes
Better use of private functions, but do not add xml comments to private functions/variables. If the function is too vague, use multiline comments to explain the code without using xml comments. If the private function obvious (private int addTwoNumbers(int a, int b)) you should not use multiline comments.
Also add a description of any parameters in a function, and a description of what a function returns (if it returns something)

2020-03-10 11:12 UTC, waffel183 commented on Assets/Scripts/Features/Gameplay/Take Photo/CreatePhotoDoubleTap.cs
> +    private void Update()
Good that you use private functions, but do not create an XML comment when using a private function/variable

2020-03-10 11:12 UTC, waffel183 commented on Assets/Scripts/Features/Gameplay/Take Photo/GeneratePhoto.cs
> +    private Texture2D ToTexture2D(RenderTexture renderTexture)
The parameter name is more descriptive, but add a description on the param like this: `<param name="renderTexture">renderTexture is used for ... </param>`
Also describe the return value: `<returns>modified texture</returns>`
[https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/returns](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/returns)

2020-03-10 13:50 UTC, waffel183 reviewed
Ignore the feedback about the XML comments on private functions, this is your own choice. This is my wrong feedback that I apologize for.

2020-03-10 13:50 UTC, waffel183 commented on Assets/Scripts/Features/Gameplay/Take Photo/CreatePhotoDoubleTap.cs
> +    private void Update()
Sorry, this is my fault. This is not a problem

2020-03-11 08:13 UTC, waffel183 approved these changes

2020-03-11 08:13 UTC, merged